name: BODHIKAH
favicon: null
layout_spectrum: 0.11968975677154958
typography_spectrum: 0.8780480048153549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.39431448886170983
  lightness: 0.33199243573471904
  saturation: 0.4805027963593602
  rhythmicContrast: 0.2556883227080107
purpose: []
